project_name: Hamburg_Segmentation
experiment_name: unetpp_efficientnet-b0_water_v1
wandb_entity: magnusmichel-universit-t-w-rzburg
system:
  device: cuda
  num_workers: 8
  seed: 42
data:
  train_dir: data
  val_split: 0.1
  img_size: 256
  mask_type: binary
  normalization_max: 4000
model:
  architecture: UnetPlusPlus
  encoder: efficientnet-b0
  weights: imagenet
  activation: null
training:
  batch_size: 16
  epochs: 10
  learning_rate: 6.0e-05
  loss_function: bce_dice
  optimizer: adamw
  use_amp: true
prediction:
  tile_size: 256
  overlap: 64
