project_name: Hamburg_Segmentation
experiment_name: unet_resnet18_water_v1
system:
  device: cuda
  num_workers: 8
  seed: 42
data:
  train_dir: data/hamburg/processed/Input
  val_split: 0.1
  input_channels:
  - 1
  - 2
  - 3
  - 4
  img_size: 256
  mask_type: binary
  normalization_max: 4000
model:
  architecture: "Unet"  # Sieht den Kontext besser
  encoder: "mit_b5"     # ResNeSt (Split-Attention) ist extrem gut für Satellitenbilder
  weights: "imagenet"
  in_channels: 4
  classes: 1
  activation: null
training:
  batch_size: 16
  epochs: 50
  learning_rate: 0.00006
  loss_function: "bce_dice"
  optimizer: adamw
  use_amp: true
